apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.Name | default .Chart.Name }}
  labels:
    app: {{ .Values.Name | default .Chart.Name }}
    name: {{ .Values.Name | default .Chart.Name }}-service
    chart: {{ .Values.Name | default .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}   
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: "gzip off;\n"
    # other valid gzip conf "gzip on;\ngzip_comp_level 5;\ngzip_http_version 1.1;\ngzip_min_length 16;\ngzip_proxied no_etag;\n",
    ingress.kubernetes.io/service-upstream: "true"
    ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingressNginxTimeout | default 60 }}"
    ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingressNginxTimeout | default 60 }}"
    ingress.kubernetes.io/proxy-body-size: '{{ .Values.ingressNginxMaxBodySize | default "1m" }}'
    nginx.org/client-max-body-size: '{{ .Values.ingressNginxMaxBodySize | default "1m" }}'
spec:
  rules:
  - host: "{{ .Values.Name | default .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.parentDomain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.Name | default .Chart.Name }}
          servicePort: 80
