apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name | default .Chart.Name }}
  labels:
    app: {{ .Values.Name | default .Chart.Name }}
    name: {{ .Values.Name | default .Chart.Name }}-service
    chart: {{ .Values.Name | default .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}   
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: {{ .Values.Name | default .Chart.Name }}
  selector:
    app: {{ .Values.Name | default .Chart.Name }}
    release: {{ .Release.Name }}
